#!/bin/bash

# $1 is the nex file that is phylip compatible to read in
# This will use JC model in dnadist, then call neighbor to find the tree.
# Lastly this script will clean up the fragmented-multi-line tree outputed
# by neighbor. (Why did they do that???)

rm -f dnadist_tmp_infile dnadist_tmp_outfile neighbor_tmp_outfile neighbor_tmp_outtree

if [ $# -ne 1 ] 
then
    echo "Must specifify phylip ready file to proccess"
    exit 0
fi

cp $1 dnadist_tmp_infile

dnadist < dnadist_JC_input 2>&1 > /dev/null
neighbor < neighbor_input 2>&1 > /dev/null
#dnadist < dnadist_JC_input
#neighbor < neighbor_input

myout=`awk '{all=all $0} END {print all}' neighbor_tmp_outtree`

echo "tree rep $myout"

rm -f dnadist_tmp_infile dnadist_tmp_outfile neighbor_tmp_outfile neighbor_tmp_outtree

